### ISSUE TITLE
Will this work on Windows?

### ISSUE THREAD

**Issue by riotrah** [brombal/just-install#2]
I know open source projects are littered with this exact request often but I haven't seen one yet. Given that there's no indication either way in this readme nor in the suggestions about this package in `just`'s documentation, yet the explicit reference to `install.sh` suggesting that it doesn't, it might be worth stating outright somewhere. 

And in addition, this issue or a follow-up could be used to track potentially adding just-install for Windows if it doesn't yet

**Comment by brombal** [comment]
Hi @riotrah, you're right that there is no support yet for Windows, but I definitely think there should be. I am happy to try and add this in the near future or accept PRs for it if you want to contribute. In the meantime I will add a note to the README that it is not supported yet. Thanks!

**Comment by brombal** [comment]
@riotrah, if you're still interested, we just published a beta version that supports Windows. You can try it out with:

```sh
npm i just-install@1.1.0-beta.0
```

I'll leave it in beta for a bit and eventually publish it as v1.1.0. I'd be very appreciative of feedback if you have time to check it out. Thanks!
